import "./globals.css";
import { workSans } from "./fonts";
import NavBar from "@/components/custom_components/NavBar";
import { Toaster } from "sonner";
import "easymde/dist/easymde.min.css";

export const metadata = {
  title: "TEST DASHBOARD :D",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={workSans.variable} suppressHydrationWarning>
        <NavBar />
        {children}
        <Toaster closeButton richColors />
      </body>
    </html>
  );
}
